name: severityPred_env
channels:
  - bioconda
  - abinit
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - abseil-cpp=20211102.0=h27087fc_1
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.8.1=py39hb9d737c_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py39hb9d737c_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - boto3=1.24.12=pyhd8ed1ab_0
  - botocore=1.27.13=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.4.26=h06a4308_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.5.18.1=py39h06a4308_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=he2f9439_0
  - coin-or-clp=1.17.6=h256e9bb_3
  - coin-or-osi=0.108.7=h3b589db_0
  - coin-or-utils=2.11.6=h573740c_0
  - coincbc=2.10.8=0_metapackage
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - curl=7.83.1=h2283fc2_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datrie=0.8.2=py39h3811e60_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.18.1=py39hf3d152e_1
  - dpath=2.0.6=py39hf3d152e_1
  - dropbox=11.32.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - filechunkio=1.8=py_2
  - filelock=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.0=py39hb9d737c_1
  - ftputil=5.0.4=pyhd8ed1ab_0
  - gcc_impl_linux-64=10.3.0=hf2f2afa_16
  - gcc_linux-64=10.3.0=hc39de41_10
  - geos=3.10.3=h27087fc_0
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=10.3.0=h73f4979_16
  - gfortran_linux-64=10.3.0=hb09a455_10
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h58526e2_0
  - google-api-core=2.8.2=pyhd8ed1ab_0
  - google-api-python-client=2.51.0=pyhd8ed1ab_0
  - google-auth=2.8.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.1=pyhd8ed1ab_0
  - google-cloud-storage=2.4.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py39h8db88ab_3
  - google-resumable-media=2.3.3=pyhd8ed1ab_0
  - googleapis-common-protos=1.56.2=py39hf3d152e_0
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.46.3=h0b91f02_1
  - grpcio=1.46.3=py39h9b22b9d_1
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=10.3.0=hf2f2afa_16
  - gxx_linux-64=10.3.0=h2593f52_10
  - harfbuzz=4.3.0=hf9f4e7c_0
  - hdf5=1.12.1=nompi_h4df4325_104
  - httplib2=0.20.4=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_resources=5.8.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.83.1=h2283fc2_0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.3.0=he6cfe16_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=15_linux64_openblas
  - liblapacke=3.9.0=15_linux64_openblas
  - libnghttp2=1.47.0=he49606f_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.1=h6239696_0
  - libsanitizer=10.3.0=h26c7422_16
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-devel_linux-64=10.3.0=he6cfe16_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_0
  - libzlib=1.2.12=h166bdaf_1
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py39hd261b2b_0
  - multidict=6.0.2=py39hb9d737c_1
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.22.4=py39hc58783e_0
  - oauth2client=4.1.3=py_0
  - openssl=3.0.3=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py39h1832856_2
  - pango=1.50.7=hbd2fdc8_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - peppy=0.31.2=pyhd8ed1ab_2
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plac=1.3.5=pyhd8ed1ab_0
  - pluggy=1.0.0=py39hf3d152e_3
  - ply=3.11=py_1
  - prettytable=3.3.0=pyhd8ed1ab_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.6.0=py39hf3d152e_1
  - py=1.11.0=pyh6c4a22f_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py39hb9d737c_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py39hf3d152e_5
  - pytest=7.1.2=py39hf3d152e_0
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-irodsclient=1.1.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - r-abind=1.4_5=r40hc72bb7e_1003
  - r-askpass=1.1=r40hcfec24a_2
  - r-backports=1.4.1=r40hcfec24a_0
  - r-base=4.0.5=h06d3f91_6
  - r-base64enc=0.1_3=r40hcfec24a_1004
  - r-bh=1.78.0_0=r40hc72bb7e_0
  - r-bit=4.0.4=r40hcfec24a_0
  - r-bit64=4.0.5=r40hcfec24a_0
  - r-bitops=1.0_7=r40hcfec24a_0
  - r-brio=1.1.3=r40hcfec24a_0
  - r-bslib=0.3.1=r40hc72bb7e_0
  - r-cachem=1.0.6=r40hcfec24a_0
  - r-callr=3.7.0=r40hc72bb7e_0
  - r-catools=1.18.2=r40h03ef668_0
  - r-cli=3.3.0=r40h7525677_0
  - r-cluster=2.1.3=r40h8da6f51_0
  - r-codetools=0.2_18=r40hc72bb7e_0
  - r-colorspace=2.0_3=r40h06615bd_0
  - r-commonmark=1.8.0=r40h06615bd_0
  - r-cowplot=1.1.1=r40hc72bb7e_0
  - r-crayon=1.5.1=r40hc72bb7e_0
  - r-crosstalk=1.2.0=r40hc72bb7e_0
  - r-curl=4.3.2=r40hcfec24a_0
  - r-data.table=1.14.2=r40hcfec24a_0
  - r-deldir=1.0_6=r40h859d828_0
  - r-desc=1.4.1=r40hc72bb7e_0
  - r-diffobj=0.3.5=r40hcfec24a_0
  - r-digest=0.6.29=r40h03ef668_0
  - r-dplyr=1.0.9=r40h7525677_0
  - r-dqrng=0.3.0=r40h03ef668_0
  - r-ellipsis=0.3.2=r40hcfec24a_0
  - r-evaluate=0.15=r40hc72bb7e_0
  - r-fansi=1.0.3=r40h06615bd_0
  - r-farver=2.1.0=r40h03ef668_0
  - r-fastmap=1.1.0=r40h03ef668_0
  - r-fitdistrplus=1.1_8=r40hc72bb7e_0
  - r-fnn=1.1.3.1=r40h7525677_0
  - r-fontawesome=0.2.2=r40hc72bb7e_0
  - r-fs=1.5.2=r40h7525677_1
  - r-future=1.23.0=r40hc72bb7e_0
  - r-future.apply=1.9.0=r40hc72bb7e_0
  - r-generics=0.1.2=r40hc72bb7e_0
  - r-ggplot2=3.3.6=r40hc72bb7e_0
  - r-ggrepel=0.9.1=r40h03ef668_0
  - r-ggridges=0.5.3=r40hc72bb7e_0
  - r-globals=0.15.0=r40hc72bb7e_0
  - r-glue=1.6.2=r40h06615bd_0
  - r-goftest=1.2_3=r40hcfec24a_0
  - r-gplots=3.1.3=r40hc72bb7e_0
  - r-gridextra=2.3=r40hc72bb7e_1003
  - r-gtable=0.3.0=r40hc72bb7e_3
  - r-gtools=3.9.2.2=r40h06615bd_0
  - r-hdf5r=1.3.5=r40h3416e65_0
  - r-here=1.0.1=r40hc72bb7e_0
  - r-hexbin=1.28.2=r40h8da6f51_0
  - r-htmltools=0.5.2=r40h03ef668_0
  - r-htmlwidgets=1.5.4=r40hc72bb7e_0
  - r-httpuv=1.6.5=r40h03ef668_0
  - r-httr=1.4.3=r40hc72bb7e_0
  - r-ica=1.0_2=r40hc72bb7e_2
  - r-igraph=1.3.2=r40hb34fc8a_0
  - r-irlba=2.3.5=r40he454529_0
  - r-isoband=0.2.5=r40h03ef668_0
  - r-jquerylib=0.1.4=r40hc72bb7e_0
  - r-jsonlite=1.8.0=r40h06615bd_0
  - r-kernsmooth=2.23_20=r40h742201e_0
  - r-labeling=0.4.2=r40hc72bb7e_1
  - r-later=1.2.0=r40h03ef668_0
  - r-lattice=0.20_45=r40hcfec24a_0
  - r-lazyeval=0.2.2=r40hcfec24a_2
  - r-leiden=0.4.2=r40hc72bb7e_0
  - r-lifecycle=1.0.1=r40hc72bb7e_0
  - r-listenv=0.8.0=r40hc72bb7e_1
  - r-lmtest=0.9_40=r40h8da6f51_0
  - r-lsei=1.3_0=r40h92ddd45_1
  - r-magrittr=2.0.3=r40h06615bd_0
  - r-mass=7.3_57=r40h06615bd_0
  - r-matrix=1.4_1=r40h0154571_0
  - r-matrixstats=0.62.0=r40h06615bd_0
  - r-mgcv=1.8_40=r40h0154571_0
  - r-mime=0.12=r40hcfec24a_0
  - r-miniui=0.1.1.1=r40hc72bb7e_1002
  - r-munsell=0.5.0=r40hc72bb7e_1004
  - r-nlme=3.1_158=r40h8da6f51_0
  - r-npsurv=0.5_0=r40hc72bb7e_0
  - r-openssl=2.0.2=r40h1f3e0c5_0
  - r-parallelly=1.32.0=r40hc72bb7e_0
  - r-patchwork=1.1.1=r40hc72bb7e_0
  - r-pbapply=1.5_0=r40hc72bb7e_0
  - r-pillar=1.7.0=r40hc72bb7e_0
  - r-pkgconfig=2.0.3=r40hc72bb7e_1
  - r-pkgload=1.2.4=r40h03ef668_0
  - r-plotly=4.10.0=r40hc72bb7e_0
  - r-plyr=1.8.7=r40h7525677_0
  - r-png=0.1_7=r40hcfec24a_1004
  - r-polyclip=1.10_0=r40h7525677_2
  - r-praise=1.0.0=r40hc72bb7e_1005
  - r-processx=3.6.1=r40h06615bd_0
  - r-progressr=0.10.1=r40hc72bb7e_0
  - r-promises=1.2.0.1=r40h03ef668_0
  - r-ps=1.7.1=r40h06615bd_0
  - r-purrr=0.3.4=r40hcfec24a_1
  - r-r6=2.5.1=r40hc72bb7e_0
  - r-rann=2.6.1=r40h03ef668_2
  - r-rappdirs=0.3.3=r40hcfec24a_0
  - r-rcolorbrewer=1.1_3=r40h785f33e_0
  - r-rcpp=1.0.8.3=r40h7525677_0
  - r-rcppannoy=0.0.19=r40h03ef668_0
  - r-rcpparmadillo=0.11.2.0.0=r40h9f5de39_0
  - r-rcppeigen=0.3.3.9.2=r40h43535f1_0
  - r-rcppparallel=5.1.5=r40h03ef668_0
  - r-rcppprogress=0.4.2=r40hc72bb7e_1
  - r-rcpptoml=0.1.7=r40h03ef668_1
  - r-rematch2=2.1.2=r40hc72bb7e_1
  - r-reshape2=1.4.4=r40h03ef668_1
  - r-reticulate=1.25=r40h7525677_1
  - r-rgeos=0.5_9=r40h40fdbc5_2
  - r-rlang=1.0.2=r40h7525677_0
  - r-rocr=1.0_11=r40hc72bb7e_1
  - r-rpart=4.1.16=r40hcfec24a_0
  - r-rprojroot=2.0.3=r40hc72bb7e_0
  - r-rspectra=0.16_1=r40h43535f1_0
  - r-rstudioapi=0.13=r40hc72bb7e_0
  - r-rtsne=0.16=r40hcec875b_0
  - r-sass=0.4.1=r40h7525677_0
  - r-scales=1.2.0=r40hc72bb7e_0
  - r-scattermore=0.8=r40hcfec24a_0
  - r-sctransform=0.3.3=r40hf361f1a_1
  - r-seurat=4.1.0=r40h03ef668_0
  - r-seuratdisk=0.0.9019=ha770c72_0
  - r-seuratobject=4.1.0=r40h7525677_0
  - r-shiny=1.7.1=r40h785f33e_0
  - r-sitmo=2.0.2=r40h03ef668_0
  - r-sourcetools=0.1.7=r40h03ef668_1002
  - r-sp=1.5_0=r40h06615bd_0
  - r-spatstat=1.64_1=r40h0357c0b_0
  - r-spatstat.core=2.4_4=r40h7525677_0
  - r-spatstat.data=2.2_0=r40hc72bb7e_0
  - r-spatstat.geom=2.4_0=r40h06615bd_0
  - r-spatstat.random=2.2_0=r40h7525677_0
  - r-spatstat.sparse=2.1_1=r40h06615bd_0
  - r-spatstat.utils=2.3_1=r40h06615bd_0
  - r-stringi=1.7.6=r40h30a9eb7_2
  - r-stringr=1.4.0=r40hc72bb7e_2
  - r-survival=3.3_1=r40h06615bd_0
  - r-sys=3.4=r40hcfec24a_0
  - r-tensor=1.5=r40hc72bb7e_1003
  - r-testthat=3.1.4=r40h7525677_0
  - r-tibble=3.1.7=r40h06615bd_0
  - r-tidyr=1.2.0=r40h03ef668_0
  - r-tidyselect=1.1.2=r40hc72bb7e_0
  - r-utf8=1.2.2=r40hcfec24a_0
  - r-uwot=0.1.11=r40h03ef668_0
  - r-vctrs=0.4.1=r40h7525677_0
  - r-viridislite=0.4.0=r40hc72bb7e_0
  - r-waldo=0.4.0=r40hc72bb7e_0
  - r-withr=2.5.0=r40hc72bb7e_0
  - r-xtable=1.8_4=r40hc72bb7e_3
  - r-yaml=2.3.5=r40h06615bd_0
  - r-zoo=1.8_10=r40h06615bd_0
  - ratelimiter=1.2.0=py_1002
  - re2=2022.04.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.0=pyhd8ed1ab_0
  - retry=0.9.2=py_0
  - rsa=4.8=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - scipy=1.7.1=py39hee8e79c_0
  - sed=4.8=he412f7d_0
  - setuptools=62.6.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.0.0=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.8.2=hdfd78af_0
  - snakemake-minimal=7.8.2=pyhdfd78af_0
  - sqlite=3.38.5=h4ff8645_0
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.7=pyhd8ed1ab_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing-extensions=4.2.0=hd8ed1ab_1
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py39hb9d737c_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39hb9d737c_2
  - yte=1.5.1=py39hf3d152e_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - absl-py==1.1.0
    - astunparse==1.6.3
    - cloudpickle==2.1.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - h5py==3.7.0
    - joblib==1.1.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - llvmlite==0.38.1
    - markdown==3.3.7
    - numba==0.55.2
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - requests-oauthlib==1.3.1
    - scikit-learn==1.0.1
    - shap==0.40.0
    - slicer==0.0.7
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - werkzeug==2.1.2
